modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/marcus8448/Project-ILE"

[[mods]]
modId="project-ile"
version="${file.jarVersion}"
displayName="Project-ILE"
#updateJSONURL="http://myurl.me/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/project-ile"
logoFile="project-ile.png"
authors="marcus8448"
description='''
Projectiles galore!
Also adds some things that have to do with projectiles.
'''
[[dependencies.project-ile]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.project-ile]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
